### ISSUE TITLE
trying to run the app 

### ISSUE THREAD

**Issue by rashedomar** [Rjtsahu/School-Bus-Tracking#16]
School-Bus-Tracking>python run.py
creating database from given mappings
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("user_login")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("user")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("kid")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("bus")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("user_type")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("feedback")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("journey")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("location")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("attendance")
2019-11-29 13:38:27,051 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,083 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-11-29 13:38:27,083 INFO sqlalchemy.engine.base.Engine SELECT count(*) AS count_1
FROM (SELECT bus.id AS bus_id, bus.name AS bus_name, bus.detail AS bus_detail, bus.vehicle_number AS bus_vehicle_number, bus.capacity AS bus_capacity, bus.is_active AS bus_is_active
FROM bus) AS anon_1
2019-11-29 13:38:27,083 INFO sqlalchemy.engine.base.Engine ()
2019-11-29 13:38:27,098 INFO sqlalchemy.engine.base.Engine SELECT count(*) AS count_1
FROM (SELECT user_type.id AS user_type_id, user_type.role_name AS user_type_role_name
FROM user_type) AS anon_1
2019-11-29 13:38:27,098 INFO sqlalchemy.engine.base.Engine ()
created mapping for tables: ['user', 'user_login', 'feedback', 'kid', 'journey', 'location', 'attendance']
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    app.config.from_pyfile('config.py')
  File "C:\Users\Rashed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\config.py", line 131, in from_pyfile
    with open(filename, mode="rb") as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): 'C:\\Users\\Rashed\\Desktop\\test\\School-Bus-Tracking\\instance\\config.py'

**Comment by Rjtsahu** [comment]
Refer this issue https://github.com/Rjtsahu/School-Bus-Tracking/issues/7

**Comment by rashedomar** [comment]
solved thx

**Comment by rskbala** [comment]
Hi Rashedomar,
Greetings.

Can you just elaborate the steps you took to install and run the app, here?  This will help all others.

**Comment by rskbala** [comment]
I was able to run the server.  In the login web page, I am not able to use "admin" credentials.  What is the user name and password? I have tried using all the users available in user/user_login tables. But no success

**Comment by Rjtsahu** [comment]
refer login function in  https://github.com/Rjtsahu/School-Bus-Tracking/blob/master/BusTrack/views/admin.py
 so you need to add ADMIN_USERNAME and ADMIN_PASSWORD key-value in config.py

**Comment by rashedomar** [comment]
you can create super user using : `python manage.py createsuperuser`

**Comment by rskbala** [comment]
Thanks. I am able to do web login but the Android app is not connecting to
the server.

**Comment by rashedomar** [comment]
you should go here :
`https://github.com/Rjtsahu/Bus-Tracking-Parent/blob/master/app/src/main/java/com/sahurjt/btsparent/network/ApiClient.java`

then change URLS

**Comment by rskbala** [comment]
I changed the URLs to point to my localhost (192.168.1.34:5000) but i think
it is not finding /api/v1/parent
