### ISSUE TITLE
help install this in heroku or pythoneverywhere

### ISSUE THREAD

**Issue by quickstreamingmedia** [Rjtsahu/School-Bus-Tracking#6]
please help this install in heroku or python everywhere

on heroku it is installed but its giving application error 

https://schooltrackgv.herokuapp.com

please provide a keynote so that can install it without issues

**Comment by Rjtsahu** [comment]
Hi,
Can u share me Heruku error logs.

**Comment by quickstreamingmedia** [comment]
yes I can also what is the default login for this ?

**Comment by quickstreamingmedia** [comment]
2018-08-24 15:32:25,497: /home/venkateshgajula/School-Bus-Tracking/BusTrack/views/admin.py:43: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
2018-08-24 15:32:25,498:   form = UserPasswordForm(request.form)
2018-08-24 15:32:25,499: [2018-08-24 15:32:25,498] ERROR in app: Exception on /admin/login [GET]
2018-08-24 15:32:25,499: Traceback (most recent call last):
2018-08-24 15:32:25,500:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1982, in wsgi_app
2018-08-24 15:32:25,500:     response = self.full_dispatch_request()
2018-08-24 15:32:25,500:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1614, in full_dispatch_request
2018-08-24 15:32:25,500:     rv = self.handle_user_exception(e)
2018-08-24 15:32:25,500:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1517, in handle_user_exception
2018-08-24 15:32:25,500:     reraise(exc_type, exc_value, tb)
2018-08-24 15:32:25,500:   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 33, in reraise
2018-08-24 15:32:25,500:     raise value
2018-08-24 15:32:25,501:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1612, in full_dispatch_request
2018-08-24 15:32:25,501:     rv = self.dispatch_request()
2018-08-24 15:32:25,501:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1598, in dispatch_request
2018-08-24 15:32:25,501:     return self.view_functions[rule.endpoint](**req.view_args)
2018-08-24 15:32:25,501:   File "/home/venkateshgajula/School-Bus-Tracking/BusTrack/views/admin.py", line 43, in login
2018-08-24 15:32:25,501:     form = UserPasswordForm(request.form)
2018-08-24 15:32:25,501:   File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 212, in __call__
2018-08-24 15:32:25,501:     return type.__call__(cls, *args, **kwargs)
2018-08-24 15:32:25,501:   File "/usr/local/lib/python3.6/dist-packages/flask_wtf/form.py", line 158, in __init__
2018-08-24 15:32:25,502:     super(Form, self).__init__(*args, **kwargs)
2018-08-24 15:32:25,502:   File "/usr/local/lib/python3.6/dist-packages/flask_wtf/form.py", line 88, in __init__
2018-08-24 15:32:25,502:     super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
2018-08-24 15:32:25,502:   File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 278, in __init__
2018-08-24 15:32:25,502:     self.process(formdata, obj, data=data, **kwargs)
2018-08-24 15:32:25,502:   File "/usr/local/lib/python3.6/dist-packages/wtforms/form.py", line 132, in process
2018-08-24 15:32:25,502:     field.process(formdata)
2018-08-24 15:32:25,502:   File "/usr/local/lib/python3.6/dist-packages/wtforms/csrf/core.py", line 43, in process
2018-08-24 15:32:25,503:     self.current_token = self.csrf_impl.generate_csrf_token(self)
2018-08-24 15:32:25,503:   File "/usr/local/lib/python3.6/dist-packages/flask_wtf/csrf.py", line 134, in generate_csrf_token
2018-08-24 15:32:25,503:     token_key=self.meta.csrf_field_name
2018-08-24 15:32:25,503:   File "/usr/local/lib/python3.6/dist-packages/flask_wtf/csrf.py", line 35, in generate_csrf
2018-08-24 15:32:25,503:     message='A secret key is required to use CSRF.'
2018-08-24 15:32:25,503:   File "/usr/local/lib/python3.6/dist-packages/flask_wtf/csrf.py", line 121, in _get_config
2018-08-24 15:32:25,503:     raise KeyError(message)
2018-08-24 15:32:25,503: KeyError: 'A secret key is required to use CSRF.'



this is error   occurred in server after I run this

**Comment by Rjtsahu** [comment]
This issue will get fixed if you add config..py,as mentioned in earlier comments
